"""Curated MCP capability catalog for PAMASMMA.

The catalog is discovery metadata only. It never auto-connects a server or treats
registry membership as a trust decision. Users/operators still choose an endpoint,
credentials, scopes and whether the connection is permitted.
"""

MCP_CAPABILITY_CATALOG: tuple[dict[str, object], ...] = (
    {
        "id": "github",
        "remote_endpoints": [{"label": "GitHub MCP", "endpoint": "https://api.githubcopilot.com/mcp/", "auth_mode": "oauth", "notes": "Use a GitHub account and grant least-privilege repository scopes."}],
        "name": "GitHub",
        "registry_server": "io.github.github/github-mcp-server",
        "priority": "core",
        "roles": ["software-ops", "executive-ops"],
        "capabilities": ["repositories", "issues", "pull-requests", "workflows", "code"],
        "auth": ["oauth", "token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Direct repository, issue and CI context for project execution and technical governance.",
    },
    {
        "id": "gitlab",
        "name": "GitLab",
        "registry_server": "io.github.dubuqingfeng/gitlab-mcp-server",
        "priority": "core",
        "roles": ["software-ops", "executive-ops"],
        "capabilities": ["projects", "issues", "merge-requests", "pipelines"],
        "auth": ["token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Provider-neutral source-control and CI/CD coverage alongside GitHub.",
    },
    {
        "id": "google-workspace",
        "remote_endpoints": [
            {"label": "Google Calendar", "endpoint": "https://calendarmcp.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires a Google OAuth client; register the exact PAMASMMA callback URL."},
            {"label": "Google Docs", "endpoint": "https://docsmcp.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires Workspace API enablement and a registered Google OAuth client."},
            {"label": "Google Sheets", "endpoint": "https://sheetsmcp.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires Workspace API enablement and a registered Google OAuth client."},
            {"label": "Google Slides", "endpoint": "https://slidesmcp.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires Workspace API enablement and a registered Google OAuth client."},
            {"label": "Google Chat", "endpoint": "https://chatmcp.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires Workspace API enablement, OAuth scopes and admin policy approval."},
            {"label": "Google People", "endpoint": "https://people.googleapis.com/mcp/v1", "auth_mode": "oauth", "notes": "Requires People API enablement and user consent."}
        ],
        "name": "Google Workspace",
        "registry_server": "com.proscendia/google-workspace",
        "registry_version": "1.0.0",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["personal-assistant", "executive-ops"],
        "capabilities": ["gmail", "drive", "calendar"],
        "auth": ["oauth"],
        "risk": "critical",
        "connection_state": "discoverable",
        "reason": "Extends PAMASMMA beyond its native Gmail + Drive integration into calendar and broader Workspace workflows.",
    },
    {
        "id": "notion",
        "remote_endpoints": [{"label": "Notion MCP", "endpoint": "https://mcp.notion.com/mcp", "auth_mode": "oauth", "notes": "Authorize the specific Notion workspace and pages needed."}],
        "name": "Notion",
        "registry_server": "com.notion/mcp",
        "registry_version": "1.0.1",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["personal-assistant", "knowledge", "executive-ops"],
        "capabilities": ["pages", "databases", "workspace-knowledge"],
        "auth": ["oauth", "token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Useful external knowledge base and operating-system context for executive memory.",
    },
    {
        "id": "slack",
        "remote_endpoints": [{"label": "Slack MCP", "endpoint": "https://mcp.slack.com/mcp", "auth_mode": "oauth", "notes": "Pre-register a Slack OAuth client; dynamic client registration is not supported by Slack. Request only required scopes."}],
        "name": "Slack",
        "registry_server": "com.mcparmory/slack",
        "registry_version": "1.0.1",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["personal-assistant", "relationship-management"],
        "capabilities": ["messages", "channels", "threads", "users"],
        "auth": ["oauth", "token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Turns PAMASMMA into a governed team communications assistant.",
    },
    {
        "id": "linear",
        "remote_endpoints": [{"label": "Linear MCP", "endpoint": "https://mcp.linear.app/mcp", "auth_mode": "oauth", "notes": "Use OAuth or a supported Linear authorization method."}],
        "name": "Linear",
        "registry_server": "app.linear/linear",
        "registry_version": "1.0.1",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["executive-ops", "project-ops"],
        "capabilities": ["issues", "projects", "teams", "cycles"],
        "auth": ["oauth"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Structured planning and execution state for product and operational work.",
    },
    {
        "id": "jira",
        "remote_endpoints": [{"label": "Atlassian Remote MCP", "endpoint": "https://mcp.atlassian.com/v2/mcp", "auth_mode": "oauth", "notes": "Authorizes the user's selected Atlassian sites and products; use least privilege."}],
        "name": "Jira",
        "registry_server": "io.github.proprock/jira-mini-mcp",
        "registry_version": "1.3.0",
        "verified_source": "official MCP Registry",
        "priority": "optional",
        "roles": ["project-ops", "software-ops"],
        "capabilities": ["issues", "search", "transitions", "projects"],
        "auth": ["token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Enterprise project-management alternative when collaborators operate in Atlassian.",
    },
    {
        "id": "sentry",
        "remote_endpoints": [{"label": "Sentry Remote MCP", "endpoint": "https://mcp.sentry.dev/mcp", "auth_mode": "oauth", "notes": "Authorize only the Sentry organization/projects required."}],
        "name": "Sentry",
        "registry_server": "io.github.getsentry/sentry-mcp",
        "registry_version": "0.41.0",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["executive-ops", "software-ops"],
        "capabilities": ["errors", "issues", "debugging", "incident-context"],
        "auth": ["token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Feeds production failure evidence into PAMASMMA's critic and decision pipeline.",
    },
    {
        "id": "grafana",
        "remote_endpoints": [{"label": "Grafana Cloud MCP", "endpoint": "https://mcp.grafana.com/mcp", "auth_mode": "oauth", "notes": "For Grafana Cloud append /<your-stack>.grafana.net to the path, for example /mcp/acme.grafana.net. Self-hosted Grafana requires deploying the open-source MCP server on an approved HTTPS host."}],
        "name": "Grafana",
        "registry_server": "io.github.grafana/mcp-grafana",
        "registry_version": "1.6.0",
        "verified_source": "official MCP Registry",
        "priority": "optional",
        "roles": ["executive-ops", "observability"],
        "capabilities": ["dashboards", "metrics", "observability"],
        "auth": ["token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Allows executive decisions to use live operational telemetry instead of anecdotes.",
    },
    {
        "id": "hubspot",
        "remote_endpoints": [{"label": "HubSpot CRM MCP", "endpoint": "https://mcp.hubspot.com", "auth_mode": "oauth", "notes": "Create an MCP Auth App with client ID/secret and PKCE; access remains scoped by HubSpot account permissions."}],
        "name": "HubSpot",
        "registry_server": "io.github.mindstone/mcp-server-hubspot",
        "registry_version": "0.4.1",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["marketing", "customer-support", "relationship-management"],
        "capabilities": ["contacts", "deals", "tickets", "marketing", "workflows"],
        "auth": ["token", "oauth"],
        "risk": "critical",
        "connection_state": "discoverable",
        "reason": "Strong fit for CRM, lead intelligence, customer support and growth execution.",
    },
    {
        "id": "figma",
        "remote_endpoints": [{"label": "Figma MCP", "endpoint": "https://mcp.figma.com/mcp", "auth_mode": "oauth", "notes": "Requires Figma account permissions and any applicable MCP client/catalog access approval."}],
        "name": "Figma",
        "registry_server": "com.figma.mcp/mcp",
        "registry_version": "1.0.3",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["content-creation", "brand", "design"],
        "capabilities": ["design-context", "assets", "files"],
        "auth": ["oauth", "token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Provides design-system and creative context for brand and product work.",
    },
    {
        "id": "canva",
        "remote_endpoints": [
            {"label": "Canva Connect MCP", "endpoint": "https://api.canva.com/connect/v1/mcp", "auth_mode": "oauth", "notes": "Use this endpoint for an approved Canva developer client; OAuth client ID/secret and approved scopes are required."},
            {"label": "Canva MCP waitlist endpoint", "endpoint": "https://mcp.canva.com/mcp", "auth_mode": "oauth", "notes": "Use only if the Canva account/client has been granted access to this endpoint."}
        ],
        "name": "Canva",
        "registry_server": "com.canva.mcp/mcp",
        "registry_version": "1.0.0",
        "verified_source": "official MCP Registry",
        "priority": "core",
        "roles": ["content-creation", "marketing", "social-media"],
        "capabilities": ["designs", "templates", "assets", "exports"],
        "auth": ["oauth", "token"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Directly supports PAMASMMA's content-creator and social-marketing responsibilities.",
    },
    {
        "id": "google-analytics",
        "remote_endpoints": [],
        "endpoint_status": "No official first-party hosted Google Analytics MCP endpoint confirmed; configure an independently reviewed third-party or self-hosted MCP adapter.",
        "verified_source": "third-party MCP Registry entry; not an official Google-hosted MCP endpoint",
        "name": "Google Analytics 4",
        "registry_server": "com.getmcpads/google-analytics",
        "registry_version": "2.0.1",
        "priority": "core",
        "roles": ["marketing", "strategy", "audience-psychology"],
        "capabilities": ["traffic", "events", "funnels", "attribution"],
        "auth": ["oauth"],
        "risk": "high",
        "connection_state": "discoverable",
        "reason": "Adds first-party behavioural evidence for campaign and audience decisions.",
    },
    {
        "id": "google-search-console",
        "remote_endpoints": [],
        "endpoint_status": "No official first-party hosted Search Console MCP endpoint confirmed; configure an independently reviewed third-party or self-hosted MCP adapter.",
        "verified_source": "third-party MCP Registry entry; not an official Google-hosted MCP endpoint",
        "name": "Google Search Console",
        "registry_server": "com.getmcpads/google-search-console",
        "registry_version": "2.0.1",
        "priority": "core",
        "roles": ["marketing", "strategy"],
        "capabilities": ["search-performance", "queries", "indexing"],
        "auth": ["oauth"],
        "risk": "medium",
        "connection_state": "discoverable",
        "reason": "Useful for SEO, demand discovery and evidence-backed content planning.",
    },
    {
        "id": "apify",
        "remote_endpoints": [{"label": "Apify MCP", "endpoint": "https://mcp.apify.com", "auth_mode": "oauth", "notes": "Hosted MCP supports OAuth or an Apify API token; apply usage limits to Actor runs."}],
        "name": "Apify",
        "registry_server": "com.apify/apify-mcp-server",
        "registry_version": "0.17.4",
        "verified_source": "official MCP Registry",
        "priority": "optional",
        "roles": ["marketing", "research", "customer-support"],
        "capabilities": ["web-extraction", "crawling", "automation"],
        "auth": ["token"],
        "risk": "critical",
        "connection_state": "discoverable",
        "reason": "Broad web-data acquisition for market research, competitive intelligence and support workflows; keep behind strict policy controls.",
    },
)


def _has_role(item: dict[str, object], role: str) -> bool:
    roles = item.get("roles")
    return isinstance(roles, list) and role in roles


def recommended_mcp_connections(
    role: str | None = None,
    priority: str | None = None,
) -> list[dict[str, object]]:
    """Return catalog entries matching optional role/priority filters."""
    entries = MCP_CAPABILITY_CATALOG
    if role:
        entries = tuple(item for item in entries if _has_role(item, role))
    if priority:
        entries = tuple(item for item in entries if item["priority"] == priority)
    return [dict(item) for item in entries]


def get_mcp_connection_profile(connection_id: str) -> dict[str, object] | None:
    """Return a copy of a catalog profile for explicit operator selection."""
    for item in MCP_CAPABILITY_CATALOG:
        if item["id"] == connection_id:
            return dict(item)
    return None
