apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: pamasmma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: pamasmma/orchestrator:v2.1.0
        ports:
        - containerPort: 3000
        env:
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: pamasmma-secrets
              key: kafka-brokers